---
- name: Package manager update and upgrade
  hosts: bramble
  become: yes
  tasks:
  - name: update all apps
    ansible.builtin.apt:
      name: "*"
      state: latest
      update_cache: yes
  - name: update dist
    ansible.builtin.apt:
      upgrade: dist

