---
- name: test-playbook
  hosts: bramble
  become: false
  gather_facts: true

  tasks:
  - name: add user ansible
    shell: "pass=$( perl -e 'print crypt('ansible')'); useradd -m -s /bin/bash -p $pass ansible; usermod -aG sudo ansible;"