---
- name: Package manager update and upgrade
  hosts: linux
  become: yes
  tasks:
  - name: update packages
    ansible.builtin.apt:
      name: "*"
      state: latest
      update_cache: yes
  - name: upgrade all packages
    ansible.builtin.apt:
      upgrade: yes
  - name: update dist
    ansible.builtin.apt:
      upgrade: dist

